[package]
name = "redarrow-client"
version = "0.1.0"
authors = ["everpcpc <git@everpcpc.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
url = "2.1"
hyper = "0.12"
futures = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
