[package]
name = "redarrow"
version = "0.4.0"
authors = ["everpcpc <git@everpcpc.com>"]
edition = "2018"

[[bin]]
name = "redarrow-client"
path = "src/client/main.rs"

[[bin]]
name = "redarrow-check"
path = "src/check/main.rs"

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
url = "2.1"
curl = "0.4.25"
serde_json = "1.0"
